# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mov-rec',
                'doc_host': 'https://daveramseymusic.github.io',
                'git_url': 'https://github.com/daveramseymusic/mov-rec',
                'lib_path': 'mov_rec'},
  'syms': {'mov_rec.core': {'mov_rec.core.foo': ('core.html#foo', 'mov_rec/core.py')}}}